### ISSUE TITLE
"invalid code section local declarations"

### ISSUE THREAD

**Issue by jedisct1** [turbolent/w2c2#108]
Hi,

Javy is a tool developed by Spotify to run Javascript in WebAssembly using QuickJS.

It ships with a QuickJS module (produced by `emit-plugin`) command, that is also attached to this issue.

When trying to transpile it,`w2c2` bails out with `"invalid code section local declarations"`:

```sh
$ w2c2 -p quickjs.wasm quickjs.c
w2c2: failed to read module quickjs.wasm: invalid code section local declarations
```

[quickjs.wasm.gz](https://github.com/user-attachments/files/18005126/quickjs.wasm.gz)

**Comment by turbolent** [comment]
That binary uses WebAssembly features not yet supported by w2c2:
- Multiple return values
- Reference types
- SIMD

```sh
$ wasm-objdump -x quickjs.wasm
// ...
Custom:
 - name: "target_features"
  - [+] bulk-memory
  - [+] multivalue
  - [+] mutable-globals
  - [+] reference-types
  - [+] sign-ext
  - [+] simd128
```

**Comment by turbolent** [comment]
See #81 for a similar report
