### ISSUE TITLE
Separated compilation sections in -fPIC?

### ISSUE THREAD

**Issue by SamuraiCrow** [turbolent/w2c2#47]
In Haiku, the parallel build mode fails to build complaining of unsupported section types.  Haiku uses a version of ELF binary that only works in Position Independent Code.  I think each binary executable is just a shared object that is called by the operating system's true executable.  Is the problem in the linker options?  Normally the internal GCC compilation just works by setting -fPIC in the compiler options and linker options automatically.  Does the W2C2 version of WASI call the ELF loader directly?

I've set an issue for myself on my fork at https://github.com/SamuraiCrow/w2c2/issues/2 if interested.

**Comment by turbolent** [comment]
> the parallel build mode fails to build complaining of unsupported section types.

Could you please post what you're running and the error your are getting?

I set up a Haiku installation now and will have a try myself, too.

**Comment by SamuraiCrow** [comment]
Approximeate steps to recreate:

1. `pkgman install gcc make devel:haiku` to download the compiler and system headers.
2. git clone w2c2 using the normal command prompt
3. `cd w2c2/w2c2`
4. `make -j8` default make for dual-threaded cores x4
5. `cd ../wasi`
6. `make FEATURES="unistd sysuio systime sysresource strndup fcntl timespec lstat" -j8`
7. `cd ../examples/python"
8. `make -j8`
9. observe:
```
cc -I../../w2c2 -O0 -g 0000000017.o 0000000065.o 0000000024.o 0000000013.o 0000000056.o 0000000012.o 0000000025.o 0000000002.o 0000000020.o 0000000077.o 0000000037.o 0000000006.o 0000000036.o 0000000078.o 0000000018.o 0000000009.o 0000000033.o 0000000035.o python.o 0000000045.o 0000000038.o 0000000031.o 0000000007.o 0000000040.o 0000000050.o 0000000060.o 0000000070.o 0000000080.o 0000000032.o 0000000026.o 0000000003.o 0000000057.o 0000000029.o 0000000054.o 0000000067.o 0000000005.o 0000000048.o 0000000064.o 0000000015.o 0000000068.o 0000000075.o 0000000041.o 0000000044.o 0000000051.o 0000000061.o 0000000071.o 0000000014.o 0000000066.o 0000000004.o 0000000019.o 0000000022.o main.o 0000000001.o 0000000010.o 0000000074.o 0000000069.o 0000000016.o 0000000079.o 0000000046.o 0000000043.o 0000000053.o 0000000027.o 0000000021.o 0000000055.o 0000000076.o 0000000063.o 0000000058.o 0000000030.o 0000000023.o 0000000073.o 0000000008.o 0000000011.o 0000000047.o 0000000039.o 0000000049.o 0000000059.o 0000000034.o 0000000042.o 0000000052.o 0000000028.o 0000000072.o 0000000062.o -o python -lm -L../../wasi -lw2c2wasi
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/11.2.0/../../../../x86_64-unknown-haiku/bin/ld: python.o:(.data.rel+0x0): undefined reference to `_binary_datasegments_start'
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'python' failed
make: *** [python] Error 1
```

## Note:
After trying the lastest version without the getentropy feature I made it farther than ever before.  The linker error above indicated the only failure in the process.  When running the makefile in Python's example directory, it indicated the following:
```
../../w2c2/w2c2 -d gnu-ld -f 100 python.wasm python.c
w2c2: skipping custom section 'name' (size 162185)
w2c2: skipping custom section 'producers' (size 123)
w2c2: skipping custom section 'target_features' (size 14)
```
Does this help the debugging?

**Comment by turbolent** [comment]
The Python Makefile enables w2c2' GNU LD mode for embedding WebAssembly data segments into the binary by default (see `-d gnu-ld`, https://github.com/turbolent/w2c2/blob/main/examples/python/Makefile#L5), which I guess should be supported in Haiku, as it uses GNU LD right?

The odd part is that the `cc` invocation should include the generated `datasegments.o` (https://github.com/turbolent/w2c2/blob/main/examples/python/Makefile#L16), but it does not seem to.

**Comment by turbolent** [comment]
This was not a Haiku-specific problem, but a non-macOS one. Turns out I had accidentally removed the `datasegments.o` file to be included. After bringing it back in https://github.com/turbolent/w2c2/commit/06461df843aa035612eb91574b2a08cd9b071465, the Python example (and other examples which uses GNU LD mode) build again, including on Haiku.

**Comment by SamuraiCrow** [comment]
Thanks!  I was scratching my head on this one!
