### ISSUE TITLE
Attempting to run w2c2 on an optimized WASI C# binary causes missing opcode error

### ISSUE THREAD

**Issue by Beyley** [turbolent/w2c2#49]
[WasiTest.wasm.zip](https://github.com/turbolent/w2c2/files/10477534/WasiTest.wasm.zip)
[OptimizedWasiTest.wasm.tar.gz](https://github.com/turbolent/w2c2/files/10477537/OptimizedWasiTest.wasm.tar.gz) 
(optimized with `wasm-opt build/WasiTest.wasm --enable-bulk-memory -o OptimizedWasiTest.wasm -O`)

```
┌─[beyley@arch] - [~/w2c2/w2c2] - [2023-01-22 11:25:14]
└─[0] <git:(main 1244998✈) > build/w2c2 OptimizedWasiTest.wasm OptimizedWasiTest.c                         
w2c2: skipping unsupported unknown section
w2c2: unsupported export: __heap_base (global)
w2c2: unsupported export: __data_end (global)
w2c2: unsupported opcode unknown (0xC1)
w2c2: failed to compile
```

**Comment by turbolent** [comment]
That opcode is from the Sign Extension proposal, https://github.com/WebAssembly/sign-extension-ops/blob/master/proposals/sign-extension-ops/Overview.md, which isn't part of the WebAssembly MVP / 1.0 spec.

Looks easy to add, will open a PR tonight.
