### ISSUE TITLE
How to access files from the binary

### ISSUE THREAD

**Issue by coolcoder613eb** [turbolent/w2c2#79]
I have built RustPython for DOS, https://github.com/coolcoder613eb/RustPython
And I want to know how make the binary accept files from the command line.
right now it says:
<img width="889" alt="Screenshot 2023-10-10 at 4 47 15 pm" src="https://github.com/turbolent/w2c2/assets/96163908/bc8dcd13-f7d0-4701-9acc-aa7c869ac585">
[ERROR rustpython_vm::vm::compile] Failed reading file 'PYBASIC.PY': No such file or directory (os error 44)

**Comment by turbolent** [comment]
Are you sure you are providing the WASI environment with a file descriptor (capability) to the directory? See e.g. https://github.com/turbolent/w2c2/blob/2e9c86f70f2fcf3374d57020389f35ea082fc018/examples/python/main.c#L211-L214

Note that paths are assumed to be WASI paths, which are Unix/POSIX paths (e.g `/foo/bar`).

What compiler are you using? DJGPP automatically translates Unix paths to the native format (`\foo\bar`)

**Comment by coolcoder613eb** [comment]
Yes, DJGPP, and i think i have fixed it, my solution also means you do not need to write out the full path.
my code in [main.c](https://github.com/coolcoder613eb/RustPython/blob/main/main.c):
```c
#ifdef __MSDOS__
    if (!wasiFileDescriptorAdd(-1, "C:\\", NULL)) {
        fprintf(stderr, "failed to add preopen\n");
        return 1;
    }
#endif
    if (!wasiFileDescriptorAdd(-2, ".", NULL)) {
        fprintf(stderr, "failed to add preopen\n");
        return 1;
    }

    if (!wasiFileDescriptorAdd(-3, "/", NULL)) {
        fprintf(stderr, "failed to add preopen\n");
        return 1;
    }
```

**Comment by coolcoder613eb** [comment]
Not really related, but how would I compile for windows 2000?
CPython3.11, and RustPython without freeze-stdlib, don't work on DOS through w2c2 because of 8.3, is there any solution?

**Comment by SamuraiCrow** [comment]
How do you run on drive D or later with your fix?

**Comment by coolcoder613eb** [comment]
I dont know, haven't tried.
