### ISSUE TITLE
`__ATOMIC_SEQ_CST` undeclared on BeOS

### ISSUE THREAD

**Issue by coolcoder613eb** [turbolent/w2c2#94]
I am trying to compile w2c2 on BeOS, but there are a lot of errors about that in `w2c2_base.h`.

**Comment by turbolent** [comment]
This is probably because the new threading related code added in #90 isn't properly gated using ifdefs, it currently assumes that a recent GCC (>=4.6) is used.

I'll try to have a look at it this weekend.

**Comment by SamuraiCrow** [comment]
Thanks for looking into this. I know BeOS uses GCC 2.95 so it cannot be on GCC 4+.

**Comment by coolcoder613eb** [comment]
I managed to get it to build a few days ago, and ported RustPython to BeOS.
