### ISSUE TITLE
Constant data is emitted not in compliance with C89 standard

### ISSUE THREAD

**Issue by whitequark** [turbolent/w2c2#98]
C89 permits only 509 characters in a logical source line:

![Screenshot_20240715_002731](https://github.com/user-attachments/assets/03f95437-9029-4ca7-8049-bd54e3e4e1ca)

w2c2 does not appear to limit line length. I am currently looking at emitted code that has a 173 kB long source line, which is definitely excessive.

**Comment by turbolent** [comment]
Though there might be limits in the standards, is this an actual problem? Did you run into particular problems with a certain (old) compiler?

**Comment by whitequark** [comment]
> Did you run into particular problems with a certain (old) compiler?

I actually ran into an issue with code editors, which generally do not enjoy having a 175 kB long line. Even `less` can struggle with inputs like this if they're big enough!

That said, this is one of the most common compatibility issues with C89.

> Though there might be limits in the standards, is this an actual problem?

In my view, if you claim adherence with C89, you need to actually follow the restrictions in the standard, or clearly document your deviation. Otherwise it is not a useful claim.
